#define PARAMETER_DELAY_LEFT 0
#define PARAMETER_DELAY_RIGHT 1
#define PARAMETER_PITCH_RATE_LEFT 2
#define PARAMETER_PITCH_RATE_RIGHT 3
#define PARAMETER_PITCH_AMOUNT_LEFT 4
#define PARAMETER_PITCH_AMOUNT_RIGHT 5
#define PARAMETER_FEEDBACK_LEFT 6
#define PARAMETER_FEEDBACK_RIGHT 7


#define PARAMETER_AMPLITUDE_RATE_LEFT 8
#define PARAMETER_AMPLITUDE_RATE_RIGHT 9
#define PARAMETER_AMPLITUDE_AMOUNT_LEFT 10
#define PARAMETER_AMPLITUDE_AMOUNT_RIGHT 11
#define PARAMETER_HIGH_PASS_LEFT 12
#define PARAMETER_HIGH_PASS_RIGHT 13
#define PARAMETER_LOW_PASS_LEFT 14
#define PARAMETER_LOW_PASS_RIGHT 15



#define PARAMETER_WIDTH 16
#define PARAMETER_WET_DRY 17

#define PARAMETER_GAIN_MASTER 18

#define PARAMETER_LR_OR_MS_PROCESSING 19
#define PARAMETER_PITCH_OSCILLATOR_PHASE 20
#define PARAMETER_AMP_OSCILLATOR_PHASE 21

#define PARAMETER_DELAY_LINK 22
#define PARAMETER_FEEDBACK_LINK 23

#define L 0
#define R 1
